name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    - cron: '42 15 * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    name: HHVM ${{matrix.hhvm}} - ${{matrix.os}}
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        hhvm:
          - '4.128'
          - latest
          - nightly
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hhvm/actions/hack-lint-test@master
        with:
          hhvm: ${{matrix.hhvm}}
          skip_lint: false
          skip_tests: true
      - name: Rebuild docs
        run: bin/hh-apidoc -o docs src
      - name: Create a pull request for generated content changes
        id: create-pr
        if: matrix.hhvm == 'nightly' && github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v4
        with:
          branch: rebuild-docs-${{matrix.hhvm}}/${{github.ref_name}}
          title: Rebuild docs with HHVM ${{matrix.hhvm}}
          commit-message: Rebuild docs with HHVM ${{matrix.hhvm}}
      - if: matrix.hhvm == 'nightly' && steps.create-pr.outputs.pull-request-number
        run: |
          echo "Changes in generated docs detected and #${{steps.create-pr.outputs.pull-request-number}} is created accordingly." >> $GITHUB_STEP_SUMMARY
          false
